// Burger Actions
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_IGREDIENTS = 'SET_IGREDIENTS';
export const FETCH_FAILED ='FETCH_FAILED';


// Orders Actions
export const PURCHARSE_BURGER_SUCCESS= 'PURCHARSE_BURGER_SUCCESS';
export const PURCHARSE_BURGER_FAIL= 'PURCHARSE_BURGER_FAIL';
export const PURCHARSE_BURGER_START= 'PURCHARSE_BURGER_START';
export const REDIRECT_ON= "REDIRECT_ON";

// feth orders 
export const FETHC_ORDER_SUCCESS= 'FECT_ORDER_SUCCESS';
export const FETHC_ORDER_FAIL= 'FECT_ORDER_FAIL';
export const FETHC_ORDER_START= 'FECT_ORDER_START';

// Auth 


export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_START= 'AUTH_START';

export const AUTH_LOGOUT='AUTH_LOGOUT';