// Burger Actions
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_IGREDIENTS = 'SET_IGREDIENTS'
export const FETCH_FAILED ='FETCH_FAILED'


// Orders Actions
export const PURCHARSE_BURGER_SUCCESS= 'PURCHARSE_BURGER_SUCCESS'
export const PURCHARSE_BURGER_FAIL= 'PURCHARSE_BURGER_FAIL'
export const PURCHARSE_BURGER_START= 'PURCHARSE_BURGER_START'
export const REDIRECT_ON= "REDIRECT_ON";
